### PR TITLE
Add language support for en, de, es, fr, hi, pt, it, ja, ru, zh and more

### PR DESCRIPTION
**Pull request by Fintasys**
closes: #203

## Description

* Generate Emoji-Set locale files from official Unicode-Org descriptions at
https://github.com/unicode-org/cldr/blob/main/common/annotations
* Add emoji set language files for en, de, es, fr, hi, pt, it, ja, ru, zh
* Update to 4.0 due to breaking changes, update ReadMe and ChangeLog

## Usage
```
EmojiPicker(
         textEditingController: _controller,
         scrollController: _scrollController,
         config: Config(
             emojiSet: _getEmojiLocale,
        ),
)

List<CategoryEmoji> _getEmojiLocale(Locale locale) {
  switch (locale.languageCode) {
    case "ja":
      return emojiSetJapanese;
    case "de":
      return emojiSetGerman;
    default:
      return emojiSetEnglish;
  }
}
```

### CODE REVIEW

**Comment by emavgl** [comment]
About the usage: wouldn't be possible to pass just the Locale object and the library behind the hood fetch the correct set?

**Comment by Fintasys** [comment]
@emavgl It's possible but it would remove the possibility to users to add other languages by their own

**Comment by emavgl** [comment]
EmojiPicker(
         textEditingController: _controller,
         scrollController: _scrollController,
         config: Config(
             emojiSet: _getEmojiLocale(locale),
        ),
)

I would still keep `emojiSet` so if the user wants to do some change, they are free to implement `_getEmojiLocale(locale)` or similar as they want to, in their app.

While in the library you already have the map Locale -> EmojiSet and you can easily achive something like

```
   config: Config(
       locale: userLocale;
  ),
```

**Comment by Fintasys** [comment]
@emavgl Ah I get it. That's of course also a possibility, thx! I will think about it and make further changes once I got time 🙏

**Comment by emavgl** [comment]
Sure, thank you so much for your work!

**Pull request merged**
