### PR TITLE
fix(android): build.gradle namespace

### PR DESCRIPTION
**Pull request by DrBu7cher**
Make it conditional, because it could break the build on Gradle < 8.0

### CODE REVIEW

**Comment by Fintasys** [comment]
@DrBu7cher Is that issue and solution documented somewhere?

**Comment by cnkygmr** [comment]
A problem occurred configuring project ':emoji_picker_flutter'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by luis901101** [comment]
> @DrBu7cher Is that issue and solution documented somewhere?

The problem being fixed by this PR is related to AGP > 8, and the solution here is compatible with older versions of AGP so the plugin will be compatible with any AGP version from >= 4.2 

check here:  https://github.com/flutter/flutter/issues/125621#issuecomment-1525995461

**Review by Fintasys — APPROVED** [review]
Thx for providing the necessary background, I wasn't aware of this issue 🙏

**Pull request merged**
