### PR TITLE
[WIP] Add Web support

### PR DESCRIPTION
**Pull request by Fintasys**
This PR adds Web to the list of supported Platforms. 

Issue: #2 

Open Issues:
* When using custom fonts, Emoji's are not correctly displayed in their text fields when selected. Solution would be custom RichTextInput like explained here https://stackoverflow.com/questions/44936239/displaying-text-with-emojis-on-flutter
* (low priority) custom font doesn't work in android/ios, probably emoji needs to be rendered at the start of the app in order to trigger loading the custom font.

### CODE REVIEW

**Comment by caleb654** [comment]
Web support would be so awesome!

**Comment by moonjoungyoung** [comment]
This will be very good. flutter web need emoji.

**Comment by moonjoungyoung** [comment]
@Fintasys 

This will be very good. flutter web needs emoji.

Is it able to use this PR for beta ..?

**Comment by dna-f** [comment]
Hi! any news on this PR?

**Comment by LostInDarkMath** [comment]
Hey @Fintasys any news on this?

**Comment by hatemragab** [comment]
i have tried it not working on the web

**Comment by Fintasys** [comment]
Closing in favor for https://github.com/Fintasys/emoji_picker_flutter/pull/103

**Pull request closed without merging**
